/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GtxGeoLocation {
    }
}
declare global {
    interface HTMLGtxGeoLocationElement extends Components.GtxGeoLocation, HTMLStencilElement {
    }
    var HTMLGtxGeoLocationElement: {
        prototype: HTMLGtxGeoLocationElement;
        new (): HTMLGtxGeoLocationElement;
    };
    interface HTMLElementTagNameMap {
        "gtx-geo-location": HTMLGtxGeoLocationElement;
    }
}
declare namespace LocalJSX {
    interface GtxGeoLocation {
    }
    interface IntrinsicElements {
        "gtx-geo-location": GtxGeoLocation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gtx-geo-location": LocalJSX.GtxGeoLocation & JSXBase.HTMLAttributes<HTMLGtxGeoLocationElement>;
        }
    }
}
